version: '3.8'

services:
  dev:
    build:
      context: .
    container_name: dev
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
